CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NCHAR(10) NOT NULL, 
    [Email] NVARCHAR(MAX) NOT NULL, 
    [phone] NUMERIC NOT NULL, 
    [time] DATETIME NOT NULL
)
